### ISSUE TITLE
Could you make LorError enum reachable from outside?

### ISSUE THREAD

**Issue by song9446** [iulianR/lordeckcodes-rs#5]
I want to handle errors..

**Comment by iulianR** [comment]
Ah, my bad. It was public but I broke that with the latest version. Going to fix it now and be more careful in the future.

**Comment by song9446** [comment]
Thanks :) BTW, I have another issue; Could you make a way(like getter functions, or declare public member) to access the CardCodeAndCount and the Card struct's inner member? I need the information of cards in decoded deck but there's no way to access to it. The original library [LoRDeckCodes](https://github.com/RiotGames/LoRDeckCodes) has that feature since the fields of CardCodeAndCount class are public.

**Comment by iulianR** [comment]
I released version 0.3 which should fix the problems you mentioned. Please let me know if you find anything else as I did not have time to use the crate in a project yet. :)
